export const addresses = [
  {
    id: 0,
    addressLine1: "455 Pacific Street",
    // addressLine2: "",
    city: "Massapequa Park",
    stateOrRegion: "NY",
    postalCode: 11762,
    countryCode: "US",
  },
  {
    id: 1,
    addressLine1: "121 W Main St",
    // addressLine2: "",
    city: "State Center",
    stateOrRegion: "IA",
    postalCode: 50247,
    countryCode: "US",
  },
  {
    id: 2,
    addressLine1: "939 W 5th Ave",
    // addressLine2: "",
    city: "Anchorage",
    stateOrRegion: "AK",
    postalCode: 99501,
    countryCode: "US",
  },
  {
    id: 3,
    addressLine1: "3312 N Berkeley Lake Rd NW",
    // addressLine2: "",
    city: "Duluth",
    stateOrRegion: "GA",
    postalCode: 30096,
    countryCode: "US",
  },
  {
    id: 4,
    addressLine1: "10920 Boggy Creek Rd",
    // addressLine2: "",
    city: "Orlando",
    stateOrRegion: "FL",
    postalCode: 32824,
    countryCode: "US",
  },
  {
    id: 5,
    addressLine1: "9525 Woodend Rd",
    // addressLine2: "",
    city: "Edwardsville",
    stateOrRegion: "KS",
    postalCode: 66111,
    countryCode: "US",
  },
  {
    id: 6,
    addressLine1: "4247 South Minnewawa Ave",
    // addressLine2: "",
    city: "Fresno",
    stateOrRegion: "California",
    postalCode: 93725,
    countryCode: "US",
  },
  {
    id: 7,
    addressLine1: "600 Industrial Dr",
    // addressLine2: "",
    city: "Lewisberry",
    stateOrRegion: "PA",
    postalCode: 17339,
    countryCode: "US",
  },
  {
    id: 8,
    addressLine1: "21639 Boord Rd",
    // addressLine2: "",
    city: "Marysville",
    stateOrRegion: "OH",
    postalCode: 43040,
    countryCode: "US",
  },
  {
    id: 9,
    addressLine1: "154 Campanelli Dr",
    // addressLine2: "",
    city: "Middleborough",
    stateOrRegion: "MA",
    postalCode: 2346,
    countryCode: "US",
  },
  {
    id: 10,
    addressLine1: "109 2nd Ave NW",
    // addressLine2: "",
    city: "Staples",
    stateOrRegion: "MN",
    postalCode: 56479,
    countryCode: "US",
  },
  {
    id: 11,
    addressLine1: "1040 Trade Ave",
    // addressLine2: "Suite 100",
    city: "Irving",
    stateOrRegion: "Texas",
    postalCode: 75261,
    countryCode: "US",
  },
  {
    id: 12,
    addressLine1: "313 W Llano Dr",
    // addressLine2: "Hobbs",
    city: "New Mexico",
    stateOrRegion: "NM",
    postalCode: 88240,
    countryCode: "US",
  },
  {
    id: 13,
    addressLine1: "2345 CENTRE STREET NE",
    // addressLine2: "",
    city: "SALEM",
    stateOrRegion: "OR",
    postalCode: 97301,
    countryCode: "US",
  },
  {
    id: 14,
    addressLine1: "2530 Meridian Pkwy suite 3016",
    // addressLine2: "",
    city: "Durham",
    stateOrRegion: "NC",
    postalCode: 27713,
    countryCode: "US",
  },
  {
    id: 15,
    addressLine1: "7055 KY-2141",
    // addressLine2: "",
    city: "Hustonville",
    stateOrRegion: "KY",
    postalCode: 40437,
    countryCode: "US",
  },
  {
    id: 16,
    addressLine1: "317 US-82",
    // addressLine2: "",
    city: "Winona",
    stateOrRegion: "MS",
    postalCode: 38967,
    countryCode: "US",
  },
  {
    id: 17,
    addressLine1: "20612 Arch Street Pike",
    // addressLine2: "",
    city: "Hensley",
    stateOrRegion: "AR",
    postalCode: 72065,
    countryCode: "US",
  },
  {
    id: 18,
    addressLine1: "111 Lincoln Ave",
    // addressLine2: "",
    city: "Underwood",
    stateOrRegion: "ND",
    postalCode: 58576,
    countryCode: "US",
  },
  {
    id: 19,
    addressLine1: "850 W 2nd St",
    // addressLine2: "",
    city: "Winner",
    stateOrRegion: "SD",
    postalCode: 57580,
    countryCode: "US",
  },
  {
    id: 20,
    addressLine1: "1200 10th Ave S",
    // addressLine2: "",
    city: "Great Falls",
    stateOrRegion: "MT",
    postalCode: 59405,
    countryCode: "US",
  },
  {
    id: 21,
    addressLine1: "692 Main St",
    // addressLine2: "",
    city: "Lander",
    stateOrRegion: "WY",
    postalCode: 82520,
    countryCode: "US",
  },
  {
    id: 22,
    addressLine1: "530 N Nevada Ave",
    // addressLine2: "",
    city: "Colorado Springs",
    stateOrRegion: "CO",
    postalCode: 80903,
    countryCode: "US",
  },
  {
    id: 23,
    addressLine1: "520 East Ave",
    // addressLine2: "",
    city: "Ketchum",
    stateOrRegion: "ID",
    postalCode: 83340,
    countryCode: "US",
  },
  {
    id: 24,
    addressLine1: "2230 N University Pkwy",
    // addressLine2: "",
    city: "Provo",
    stateOrRegion: "UT",
    postalCode: 84604,
    countryCode: "US",
  },
  {
    id: 25,
    addressLine1: "19780 Hitching Post Way",
    // addressLine2: "",
    city: "Cordes Lakes",
    stateOrRegion: "AZ",
    postalCode: 86333,
    countryCode: "US",
  },
  {
    id: 26,
    addressLine1: "1100 5th Ave",
    // addressLine2: "",
    city: "Seattle",
    stateOrRegion: "WA",
    postalCode: 98101,
    countryCode: "US",
  },
  {
    id: 27,
    addressLine1: "3308 Route 940",
    // addressLine2: "",
    city: "Mount Pocono",
    stateOrRegion: "PA",
    postalCode: 18344,
    countryCode: "US",
  },
  {
    id: 28,
    addressLine1: "2310 Kuhio Ave #124",
    // addressLine2: "",
    city: "Honolulu",
    stateOrRegion: "hi",
    postalCode: 96815,
    countryCode: "US",
  },
  {
    id: 29,
    addressLine1: "86 Lackawanna Ave",
    // addressLine2: "",
    city: "Woodland Park",
    stateOrRegion: "NJ",
    postalCode: 7424,
    countryCode: "US",
  },
  {
    id: 30,
    addressLine1: "NE 172ND PI",
    // addressLine2: "",
    city: "Woodinville",
    stateOrRegion: "Washington",
    postalCode: 98072,
    countryCode: "US",
  },
  {
    id: 31,
    addressLine1: "16 Applegate Dr",
    // addressLine2: "",
    city: "Robbinsville",
    stateOrRegion: "NJ",
    postalCode: 8691,
    countryCode: "US",
  },
  {
    id: 32,
    addressLine1: "1336 Old Lancaster Pike",
    // addressLine2: "",
    city: "Hockessin",
    stateOrRegion: "de",
    postalCode: 19707,
    countryCode: "US",
  },
  {
    id: 33,
    addressLine1: "110 Rue Magnolia",
    // addressLine2: "",
    city: "Biloxi",
    stateOrRegion: "ms",
    postalCode: 39530,
    countryCode: "US",
  },
  {
    id: 34,
    addressLine1: "153 S Illinois St",
    // addressLine2: "",
    city: "Indianapolis",
    stateOrRegion: "in",
    postalCode: 46225,
    countryCode: "US",
  },
  {
    id: 35,
    addressLine1: "2010 Clipper Park Rd Suite 126",
    // addressLine2: "",
    city: "Baltimore",
    stateOrRegion: "md",
    postalCode: 21211,
    countryCode: "US",
  },
  {
    id: 36,
    addressLine1: "4702 South 27th Street",
    // addressLine2: "",
    city: "Omaha",
    stateOrRegion: "NE",
    postalCode: 68107,
    countryCode: "US",
  },
  {
    id: 37,
    addressLine1: "713 St Louis St",
    // addressLine2: "",
    city: "New Orleans",
    stateOrRegion: "la",
    postalCode: 70130,
    countryCode: "US",
  },
  {
    id: 38,
    addressLine1: "2900 Virginia Ave",
    // addressLine2: "",
    city: "St  Louis",
    stateOrRegion: "MO",
    postalCode: 63118,
    countryCode: "US",
  },
  {
    id: 39,
    addressLine1: "1110 Market St",
    // addressLine2: "",
    city: "Chattanooga",
    stateOrRegion: "TN",
    postalCode: 37402,
    countryCode: "US",
  },
  {
    id: 40,
    addressLine1: "900 American Rd",
    // addressLine2: "",
    city: "Lansing",
    stateOrRegion: "mi",
    postalCode: 48911,
    countryCode: "US",
  },
  {
    id: 41,
    addressLine1: "4837 MacCorkle Ave SW",
    // addressLine2: "",
    city: "South Charleston",
    stateOrRegion: "wv",
    postalCode: 25309,
    countryCode: "US",
  },
  {
    id: 42,
    addressLine1: "760 West Crossroads Pkwy",
    // addressLine2: "Suite 100",
    city: "Bolingbrook",
    stateOrRegion: "Illinois",
    postalCode: 60490,
    countryCode: "US",
  },
  {
    id: 43,
    addressLine1: "36 Jaime Ct",
    // addressLine2: "",
    city: "Old Bridge",
    stateOrRegion: "NJ",
    postalCode: 8857,
    countryCode: "US",
  },
];
